services:
  app:
    image: github.com/a10adotapp/react-waiter
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    container_name: react-waiter-app
    command: sleep infinity
    volumes:
      - .npm:/home/vscode/.npm
      - ..:/home/vscode/react-waiter
